// const secretMessage = atob(
//   'SGF2ZSB0aGUgbW9zdCBhbWF6aW5nIGJpcnRoZGF5IEV6aXdhbm5lLCB5b3UgYXJlIGEgdHJ1ZSBpbnNwaXJhdGlvbiEgWW91ciBraW5kbmVzcyBhbmQgYnJpbGxpYW5jZSBtYWtlIHRoZSB3b3JsZCBhIGJldHRlciBwbGFjZS4gUFMuIFlvdSdyZSB0aGUgY29vbGVzdCBiYWNrZW5kIGRldmVsb3BlciBJIGtub3cgd2l0aCBhIGN1dGUgbGF1Z2gh',
// );

// console.log(secretMessage);
